name: manipforce
channels:
  - conda-forge
  - pkgs/main
  - pytorch
  - nvidia
dependencies:
  - accelerate
  - diffusers
  - dill
  - einops
  - hydra-core
  - imagecodecs
  - numpy==1.26.4
  - pandas
  - python=3.10
  - pytorch==2.1.0
  - pytorch-cuda=11.8
  - threadpoolctl
  - timm
  - torchaudio==2.1.0
  - torchvision==0.16.0
  - tqdm
  - wandb
  - zarr
  - pip:
    - docker-pycreds==0.4.0
    - intel-cmplr-lib-ur==2025.3.2
    - intel-openmp==2023.2.4
    - mkl==2023.2.0
    - onemkl-license==2025.3.1
    - scipy==1.15.3
    - tbb==2021.13.1
    - tcmlib==1.4.1
    - torchcde==0.2.5
    - torchdiffeq==0.2.5
    - torchsde==0.2.6
    - trampoline==0.1.2
    - umf==1.0.3


